name: CODZombie
version: ${project.version}
main: codzombie.codzombie.CODZombie
api-version: 1.13
author: x33120411@gmail.com
commands:
  reset:
  RecordMode:
  StartGame:
  CoinWallRecord:
  SaveCoinWall:
  UnlimitedMode:
  RegisterStore:
  CODGive:
  SetCoin:
  CoinWallNext:
  DisplayNameStand:

